version: '3.8'

services:
  web:
    image: your-image-name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Укажите порт, на который должен быть привязан ваш контейнер
